export const ERROR_CODES = {
  INVALID_SNAPSHOT: 'INVALID_SNAPSHOT',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  CIRCULAR_REFERENCE: 'CIRCULAR_REFERENCE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export const WARNING_CODES = {
  UNKNOWN_FIELD_TYPE: 'UNKNOWN_FIELD_TYPE',
  MULTIPLE_PRIMARY_KEYS: 'MULTIPLE_PRIMARY_KEYS',
  INCOMPLETE_RELATION: 'INCOMPLETE_RELATION',
  DANGLING_RELATION: 'DANGLING_RELATION',
  DUPLICATE_VIRTUAL_FIELD: 'DUPLICATE_VIRTUAL_FIELD',
  CIRCULAR_REFERENCE_DETECTED: 'CIRCULAR_REFERENCE_DETECTED',
} as const;

export const SYSTEM_COLLECTION_PREFIX = 'directus_';
export const DEFAULT_MAX_SIZE_BYTES = 50 * 1024 * 1024; // 50MB
export const DEFAULT_MAX_DEPTH = 100;
export const SUPPORTED_SNAPSHOT_VERSIONS = [1, 4] as const;
